#!/usr/bin/env python3
# encoding: utf-8

def build(bld):
    bld.ap_stlib(
        name='hacl',
        ap_vehicle_project=False,
        ap_libraries=[],
        includes=[
            'include',
            'include/krml',
            'include/krml/internal', 
            'include/internal',
        ],
        export_includes=[
            'include',
            'include/krml',
            'include/krml/internal',
            'include/internal', 
        ],
        source=[
            'src/Hacl_AEAD_Chacha20Poly1305.c',
            'src/Hacl_Chacha20.c', 
            'src/Hacl_MAC_Poly1305.c',
        ]
    )