#!/usr/bin/env python3

def build(bld):
    vehicle = bld.path.name

    # Librerías comunes del vehículo (igual que ya estaba)
    bld.ap_stlib(
        target=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AC_AttitudeControl',
            'AC_InputManager',
            'AC_PrecLand',
            'AC_Sprayer',
            'AC_Autorotation',
            'AC_WPNav',
            'AP_Camera',
            'AP_IRLock',
            'AP_Motors',
            'AP_Avoidance',
            'AP_AdvancedFailsafe',
            'AP_SmartRTL',
            'AP_WheelEncoder',
            'AP_Winch',
            'AP_LTM_Telem',
            'AP_Devo_Telem',
            'AC_AutoTune',
            'AP_KDECAN',
            'AP_SurfaceDistance',
        ],
    )

    # --- NUEVA librería: ascon ---
    ASCON_SRC = [
        '../libraries/ascon/aead.c',
        '../libraries/ascon/ascon_ctx.cpp',
    ]
    ASCON_INC = [
        '../libraries/ascon',
    ]

    bld.ap_library(
        target='ascon',          # <- en ArduPilot es 'target', no 'name'
        src=ASCON_SRC,
        includes=ASCON_INC,
    )

    # Binario multicóptero
    bld.ap_program(
        target='arducopter',                 # <- no 'program_name'
        program_groups=['bin', 'copter'],
        use=[vehicle + '_libs', 'ascon'],    # <- enlaza contra la lib ascon
        defines=['FRAME_CONFIG=MULTICOPTER_FRAME', 'AP_MAVLINK_ENCRYPT'],
        # si necesitas que los headers de ascon estén visibles aquí también:
        includes=ASCON_INC,
    )

    # Binario heli
    bld.ap_program(
        target='arducopter-heli',
        program_groups=['bin', 'heli'],
        use=[vehicle + '_libs', 'ascon'],
        defines=['FRAME_CONFIG=HELI_FRAME', 'AP_MAVLINK_ENCRYPT'],
        includes=ASCON_INC,
    )


