#!/usr/bin/env python3

def build(bld):
    vehicle = bld.path.name

    # 1) Libs estándar del vehículo (igual que antes)
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AC_AttitudeControl',
            'AC_InputManager',
            'AC_PrecLand',
            'AC_Sprayer',
            'AC_Autorotation',
            'AC_WPNav',
            'AP_Camera',
            'AP_IRLock',
            'AP_Motors',
            'AP_Avoidance',
            'AP_AdvancedFailsafe',
            'AP_SmartRTL',
            'AP_WheelEncoder',
            'AP_Winch',
            'AP_LTM_Telem',
            'AP_Devo_Telem',
            'AC_AutoTune',
            'AP_KDECAN',
            'AP_SurfaceDistance',
        ],
    )

    # 2) NUEVA librería: ascon  (añade aquí todos tus .c/.cpp reales)
    ASCON_SRC = [
        '../libraries/ascon/aead.c',
        '../libraries/ascon/ascon_ctx.cpp',
    ]
    ASCON_INC = [
        '../libraries/ascon',
    ]
    bld.ap_library(
        name='ascon',
        src=ASCON_SRC,
        includes=ASCON_INC,
    )

    # 3) Programas: enlazar también contra 'ascon'
    bld.ap_program(
        program_name='arducopter',
        program_groups=['bin', 'copter'],
        use=[vehicle + '_libs', 'ascon'],   # <- aquí usamos la lib
        defines=['FRAME_CONFIG=MULTICOPTER_FRAME', 'AP_MAVLINK_ENCRYPT'],
    )

    bld.ap_program(
        program_name='arducopter-heli',
        program_groups=['bin', 'heli'],
        use=[vehicle + '_libs', 'ascon'],   # <- también aquí
        defines=['FRAME_CONFIG=HELI_FRAME'],
    )

